/**
 * @fileoverview Templates for package-root JSON files (package.json,
 * package.exports.json) and the package entry point (src/index.ts).
 *
 * @module creator/templates/package
 */

/**
 * Generates a new package.json for a scaffolded nice-react-* component package.
 *
 * @param {string} packageName - Full npm name (e.g. "nice-react-lightbox")
 * @returns {string} Pretty-printed JSON ending with a newline
 */
function packageJson(packageName) {
  return JSON.stringify({
    name: packageName,
    version: '0.1.0',
    type: 'module',
    description: '',
    main: 'dist/index.js',
    module: 'dist/index.esm.js',
    types: 'dist/index.d.ts',
    files: ['dist'],
    scripts: {
      build: 'rollup -c',
      dev: 'rollup -c -w',
      typecheck: 'tsc --noEmit',
      'generate-exports': 'nice-generate-exports .',
      prepublishOnly: 'npm run build',
      prepare: 'npm run build',
    },
    keywords: ['react', 'component', 'nice-react'],
    author: '',
    license: 'MIT',
    dependencies: {
      'nice-react-styles': 'file:../react-styles',
    },
    peerDependencies: {
      react: '>=19.2.0 <20.0.0',
      'react-dom': '>=19.2.0 <20.0.0',
      'styled-components': '>=6.1.18 <7.0.0',
    },
    devDependencies: {
      'nice-configuration': 'file:../configuration',
      react: '19.2.0',
      'react-dom': '19.2.0',
      'styled-components': '6.1.19',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      '@rollup/plugin-commonjs': '^25.0.7',
      '@rollup/plugin-node-resolve': '^15.2.3',
      '@rollup/plugin-typescript': '^11.1.5',
      rollup: '^4.9.1',
      'rollup-plugin-dts': '^6.1.0',
      'rollup-plugin-peer-deps-external': '^2.2.4',
      tslib: '^2.6.2',
      typescript: '^5.5.0',
    },
  }, null, 2) + '\n';
}

/**
 * Export generator config (package.exports.json).
 *
 * Declares the package's public export surface. The nice-generate-exports
 * CLI reads this file and writes src/index.ts. See
 * nice-configuration/src/exports/ for the generator and schema.
 *
 * @param {string} componentName - PascalCase component name
 * @returns {string}
 */
function packageExportsJson(componentName) {
  return JSON.stringify({
    $schema: '../configuration/src/exports/schema.json',
    default: componentName,
    components: [componentName],
    tokens: [componentName],
  }, null, 2) + '\n';
}

/**
 * Package entry point (src/index.ts).
 *
 * Output matches what nice-generate-exports produces so the initial
 * scaffolded file is already in sync with the generator. After the
 * first `npm run generate-exports`, the generator owns this file.
 *
 * @param {string} componentName - PascalCase component name
 * @returns {string}
 */
function srcIndex(componentName) {
  return `// GENERATED by nice-generate-exports — do not edit by hand
// To update: edit package.exports.json and run \`npm run generate-exports\`

export { default } from "./components/${componentName}"
export * from "./components/${componentName}"
export { ${componentName}Styles, get${componentName}Token } from "./tokens"
`;
}

module.exports = { packageJson, packageExportsJson, srcIndex };
