/**
 * @fileoverview File system watcher for linked package dist folders
 *
 * Watches the dist/ folders of all linked packages and triggers a reload
 * in the consuming project when changes are detected. This enables hot-reload
 * functionality for webpack/CRA projects that don't have native symlink watching.
 *
 * Strategy:
 * 1. Discover all file: linked packages
 * 2. Watch their dist/ folders for changes
 * 3. When changes detected, touch a trigger file in the consuming project
 * 4. Webpack/CRA detects the trigger file change and recompiles
 *
 * @module watcher
 */

const fs = require('fs');
const path = require('path');
const { findAllLinkedPackages } = require('./discovery');
const { removeFile, getPackageName } = require('../shared/fs-utils');
const { log, info, success, warn, cyan, gray } = require('../shared/logger');

// ──────────────────────────────────────────────────────────────────────────────
// Constants
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Name of the trigger file that gets touched to trigger webpack recompilation
 * @constant {string}
 */
const TRIGGER_FILE_NAME = '.symlink-trigger.js';

/**
 * Content for the trigger file (exports a timestamp)
 * @constant {string}
 */
const TRIGGER_FILE_CONTENT = `// Auto-generated by nice-toolkit --watch
// This file is touched when linked packages change to trigger recompilation
// Add this file to .gitignore
export const SYMLINK_TRIGGER_TIMESTAMP = `;

/**
 * Debounce delay in milliseconds
 * @constant {number}
 */
const DEBOUNCE_DELAY = 300;

// ──────────────────────────────────────────────────────────────────────────────
// Debouncer
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Creates a keyed debouncer that batches calls by key
 *
 * @param {number} delay - Debounce delay in milliseconds
 * @returns {{ call: (key: string, fn: (count: number) => void) => void }}
 */
function createKeyedDebouncer(delay) {
  const timers = new Map();
  const counts = new Map();

  return {
    call(key, fn) {
      counts.set(key, (counts.get(key) || 0) + 1);

      const existing = timers.get(key);
      if (existing) {
        clearTimeout(existing);
      }

      const timer = setTimeout(() => {
        const count = counts.get(key) || 1;
        timers.delete(key);
        counts.delete(key);
        fn(count);
      }, delay);

      timers.set(key, timer);
    },
  };
}

// ──────────────────────────────────────────────────────────────────────────────
// Trigger File Management
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Gets the path to the trigger file in the project's src directory
 *
 * @param {string} projectDir - Project root directory
 * @returns {string} Absolute path to trigger file
 */
function getTriggerFilePath(projectDir) {
  return path.join(projectDir, 'src', TRIGGER_FILE_NAME);
}

/**
 * Creates or updates the trigger file with a new timestamp
 *
 * @param {string} projectDir - Project root directory
 * @param {string} changedPackage - Name of the package that changed
 */
function touchTriggerFile(projectDir, changedPackage) {
  const triggerPath = getTriggerFilePath(projectDir);
  const timestamp = Date.now();
  const content = `${TRIGGER_FILE_CONTENT}${timestamp};\n// Last change: ${changedPackage} at ${new Date(timestamp).toISOString()}\n`;

  try {
    fs.writeFileSync(triggerPath, content, 'utf-8');
  } catch (e) {
    warn(`Could not write trigger file: ${e.message}`);
  }
}


/**
 * Ensures the trigger file exists and is imported by the app
 *
 * @param {string} projectDir - Project root directory
 * @returns {boolean} True if trigger file was created/verified
 */
function ensureTriggerFile(projectDir) {
  const triggerPath = getTriggerFilePath(projectDir);
  const srcDir = path.join(projectDir, 'src');

  // Check if src directory exists
  if (!fs.existsSync(srcDir)) {
    warn(`No src/ directory found in ${projectDir}`);
    return false;
  }

  // Create trigger file if it doesn't exist
  if (!fs.existsSync(triggerPath)) {
    const timestamp = Date.now();
    const content = `${TRIGGER_FILE_CONTENT}${timestamp};\n// Created by nice-toolkit --watch\n`;
    fs.writeFileSync(triggerPath, content, 'utf-8');
    info(`Created trigger file: ${gray(TRIGGER_FILE_NAME)}`);
    info(`Add to your entry file: ${cyan(`import './${TRIGGER_FILE_NAME}'`)}`);
    info(`Add to .gitignore: ${cyan(TRIGGER_FILE_NAME)}`);
  }

  return true;
}

// ──────────────────────────────────────────────────────────────────────────────
// Package Watcher
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Watches a single package's dist folder
 *
 * @param {string} pkgPath - Absolute path to package
 * @param {string} watchDir - Subdirectory to watch (e.g., 'dist')
 * @param {(pkgName: string) => void} onChange - Callback when changes detected
 * @returns {fs.FSWatcher | null} Watcher instance or null if failed
 */
function watchPackage(pkgPath, watchDir, onChange) {
  const distPath = path.join(pkgPath, watchDir);
  const pkgName = getPackageName(pkgPath);

  if (!fs.existsSync(distPath)) {
    warn(`No ${watchDir}/ folder in ${pkgName} - run 'npm run dev' in that package`);
    return null;
  }

  try {
    const watcher = fs.watch(distPath, { recursive: true }, (eventType, filename) => {
      if (filename) {
        onChange(pkgName);
      }
    });

    watcher.on('error', (error) => {
      warn(`Watcher error for ${pkgName}: ${error.message}`);
    });

    return watcher;
  } catch (e) {
    warn(`Could not watch ${pkgName}: ${e.message}`);
    return null;
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Main Watch Function
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Watch options
 * @typedef {object} WatchOptions
 * @property {string} [watchDir='dist'] - Subdirectory to watch in each package
 * @property {number} [debounce=300] - Debounce delay in milliseconds
 * @property {boolean} [verbose=false] - Log detailed change information
 */

/**
 * Starts watching all linked packages and triggers recompilation on changes
 *
 * @param {string} projectDir - Project root directory
 * @param {WatchOptions} [options={}] - Watch configuration
 * @returns {{ stop: () => void }} Controller to stop watching
 *
 * @example
 * const controller = startWatching('/path/to/my-app', { verbose: true });
 * // Later...
 * controller.stop();
 */
function startWatching(projectDir, options = {}) {
  const { watchDir = 'dist', debounce = DEBOUNCE_DELAY, verbose = false } = options;

  // Find all linked packages
  const allLinkedPackages = findAllLinkedPackages(projectDir);

  if (allLinkedPackages.size === 0) {
    warn('No linked packages found. Nothing to watch.');
    return { stop: () => {} };
  }

  // Filter to only packages with the watch directory
  const linkedPackages = Array.from(allLinkedPackages).filter((pkgPath) => {
    const distPath = path.join(pkgPath, watchDir);
    if (!fs.existsSync(distPath)) {
      const pkgName = getPackageName(pkgPath);
      info(`Skipping ${pkgName} (no ${watchDir}/ folder)`);
      return false;
    }
    return true;
  });

  if (linkedPackages.length === 0) {
    warn(`No packages have ${watchDir}/ folders. Nothing to watch.`);
    return { stop: () => {} };
  }

  // Ensure trigger file exists
  if (!ensureTriggerFile(projectDir)) {
    warn('Could not set up trigger file. Watch mode may not work correctly.');
  }

  // Log what we're watching
  log(`Watching ${cyan(linkedPackages.length)} linked packages:\n`);
  for (const pkgPath of linkedPackages) {
    const pkgName = getPackageName(pkgPath);
    console.log(`  ${gray('•')} ${pkgName}`);
  }
  console.log('');

  // Create debouncer
  const debouncer = createKeyedDebouncer(debounce);

  // Start watchers
  const watchers = [];

  for (const pkgPath of linkedPackages) {
    const watcher = watchPackage(pkgPath, watchDir, (pkgName) => {
      debouncer.call(pkgName, (fileCount) => {
        const files = fileCount === 1 ? 'file' : 'files';

        if (verbose) {
          info(`${pkgName} changed (${fileCount} ${files})`);
        }

        touchTriggerFile(projectDir, pkgName);
        success(`Triggered reload for ${cyan(pkgName)}`);
      });
    });

    if (watcher) {
      watchers.push(watcher);
    }
  }

  if (watchers.length === 0) {
    warn('No packages could be watched. Ensure they have dist/ folders.');
    return { stop: () => {} };
  }

  success(`Watching ${watchers.length} packages. Press Ctrl+C to stop.\n`);

  // Return controller
  return {
    stop() {
      for (const watcher of watchers) {
        watcher.close();
      }
      info('Stopped watching linked packages');
    },
  };
}

/**
 * Removes the trigger file from the project
 *
 * @param {string} projectDir - Project root directory
 */
function cleanupTriggerFile(projectDir) {
  const triggerPath = getTriggerFilePath(projectDir);

  if (fs.existsSync(triggerPath)) {
    removeFile(triggerPath);
    info(`Removed trigger file: ${TRIGGER_FILE_NAME}`);
  }
}

module.exports = {
  // Constants
  TRIGGER_FILE_NAME,
  DEBOUNCE_DELAY,

  // Functions
  startWatching,
  cleanupTriggerFile,
  ensureTriggerFile,
  getTriggerFilePath,
};